### ISSUE TITLE
Iterm2, terminal, friends colors

### ISSUE THREAD

**Issue by rojspencer** [itchyny/landscape.vim#4]
Any possibility of a terminal color scheme to compliment this?

Or recommendation for configuring the colors manually?

**Comment by itchyny** [comment]
I do not understand what you mean by `friends colors`.

**Comment by rojspencer** [comment]
Friends of iterm2, terminal -- gnome-terminal, konsole, xterm -- i.e. terminal emulators.

Most allow for a color scheme to be imported and used.  Most vim color schemes don't though.

As an example of one that does though, base16 has a vim color scheme [base16-vim](https://github.com/chriskempson/base16-vim) and a terminal color scheme to match [base16](https://github.com/chriskempson/base16).

Curious if you'd thought of doing the same.

**Comment by itchyny** [comment]
Sorry but I'm not interested in creating the colorschemes for terminals. But I do not mind if you export the colors of landscape.
