### ISSUE TITLE
List characters not visible

### ISSUE THREAD

**Issue by rojspencer** [itchyny/landscape.vim#5]
When I run `:set list` list characters are not visible.  Switching to almost any other color scheme allows me to see them.

Relevant info:
Terminal vim 7.4.898 on OS/X

    set listchars=tab:→\ ,eol:⤦,trail:·,extends:↷,precedes:↶

**Comment by itchyny** [comment]
I do not like the `~` at the bottom of files. You can enable the highlight by the following config.
`highlight NonText ctermfg={your favorite colour}`
