### ISSUE TITLE
Questions about design choices for preprocessor related highlighting

### ISSUE THREAD

**Issue by yhu266** [itchyny/landscape.vim#6]
I noticed that the author used different colors for preprocessor related highlighting:
https://github.com/itchyny/landscape.vim/blob/566d16ee4faf6787f1e98dbf22ddb1c04482560d/colors/landscape.vim#L29-L33
which is different from the default settings (all colors are the same and linked to `PreProc`)

What is the motive to use different colors here, given these groups share similar traits in terms of code readability?

**Comment by itchyny** [comment]
I do want to differentiate them so I use different colors. That's all.

|1|2|
|--|--|
|<img width="716" alt="Screen Shot 2020-11-08 at 19 14 32" src="https://user-images.githubusercontent.com/375258/98462289-a347df80-21f6-11eb-9e22-1d9e71bcde2f.png">|<img width="705" alt="Screen Shot 2020-11-08 at 19 15 12" src="https://user-images.githubusercontent.com/375258/98462298-ba86cd00-21f6-11eb-8a9b-0e2d0d50d72e.png">|

**Comment by yhu266** [comment]
I see. Do you have recommended material for editor colorscheme design? Or is it more of a trial-and-error approach?

**Comment by itchyny** [comment]
I'm not a pro of such area. But there are many color palette generators online.
